# Generated by Django 3.2.3 on 2021-05-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='text',
        ),
    ]
