# Generated by Django 3.2.3 on 2021-06-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_management_app', '0002_rename_name_team_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='text',
            new_name='name',
        ),
    ]
