# Generated by Django 3.2.3 on 2021-06-11 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('football_management_app', '0004_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('photo', models.ImageField(upload_to='media')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_management_app.team')),
            ],
        ),
    ]
