# Generated by Django 3.2.3 on 2021-06-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_management_app', '0005_auto_20210611_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
